### ISSUE TITLE
Display only files with errors

### ISSUE THREAD

**Issue by minhlab** [smartschat/cort#15]
Is it possible to visualize only files that contain at least one error? I have a large corpus and after filtering there are only a couple hundreds of errors. So I find myself looking at clean files most of the time (i.e. no annotations besides mention spans).

**Comment by smartschat** [comment]
You need to modify cort/analysis/visualization.py.

I've created a gist for the modified file: https://gist.github.com/smartschat/85a892c1752129d9f553d716abe9cb1b

Does it work for you?

**Comment by minhlab** [comment]
No, it creates an empty window :-(

<img width="701" alt="screen shot 2017-05-01 at 11 52 23" src="https://cloud.githubusercontent.com/assets/2816631/25577204/b1532230-2e64-11e7-8d97-41c2912f2b81.png">

**Comment by smartschat** [comment]
I've updated the gist, it should work now.

**Comment by minhlab** [comment]
Thanks, it's beautiful!

**Comment by smartschat** [comment]
You're welcome! I'll add this to cort's main branch later (with proper documentation and logging).
