### ISSUE TITLE
Code not working directly

### ISSUE THREAD

**Issue by preritjain** [smartschat/cort#5]
I was using model-pair-train.obj model provided in your repository. On running the command provided for coreference resolution for raw data, I got the following error.
`
Traceback (most recent call last):
  File "/usr/local/bin/cort-predict-raw", line 132, in <module>
    testing_corpus = p.run_on_docs("corpus", args.input_filename)
  File "/usr/local/lib/python3.4/dist-packages/cort/preprocessing/pipeline.py", line 38, in run_on_docs
    codecs.open(doc, "r", "utf-8")
  File "/usr/local/lib/python3.4/dist-packages/cort/preprocessing/pipeline.py", line 82, in run_on_doc
    pdeprel=None
TypeError: __new__() missing 1 required positional argument: 'extra'
`
This got resolved when I added a line 
`extra = None`
following line 82 in cort/preprocessing/pipeline.py

**Comment by chardmeier** [comment]
Confirmed.

**Comment by smartschat** [comment]
Thanks for reporting the issue! In v0.3.1, PyStanfordDependencies' API has changed, I'll have to make sure that it works with both versions of the API. I'll update cort ASAP.

Edit: I've decided otherwise, cort will now require PyStanfordDependencies v0.3.1.
