### ISSUE TITLE
error visualization problems

### ISSUE THREAD

**Issue by isimova** [smartschat/cort#9]
Hello,
I encounter a problem when trying to visualize a system's recall errors by type, as described in the documentation. My reference and system files are in conll, no errors are displayed when running the code, but the resulting html file doesn't display the document text and any fields in the left panel except for "Documents". When the jquery and jquery.jsPlumb imports in the html file are commented out, everything is correctly displayed (document text, left panel, and gold/system mention boundaries), but without the possibility to interact. Reproduced in the latest Firefox and chrome; python 2.7. The visualization of a document processed with cort-predict-raw seems to work fine. 
Thanks!

**Comment by smartschat** [comment]
It works fine for me (Chrome 53.0.2785.143 (64-bit), Python 2.7.12). Could you send me a minimal working example that reproduces the bug (including the HTML stuff and the conll files)?

**Comment by isimova** [comment]
I reproduced the issue with python3. Here are the input files, code, and resulting html.
Thanks!
[visualization_problem.zip](https://github.com/smartschat/cort/files/514472/visualization_problem.zip)

**Comment by smartschat** [comment]
Thanks for reporting the bug! Apparently the punctuation mark "." in the document's name confuses jQuery. If I change all occurrences of ".xml" to "xml", the document is displayed as it should be. 

Hence, as a fix, you should rename the document identifiers such that no "." is contained. I'll have a closer look into what other tokens could break the visualization and I'll fix cort accordingly.

**Comment by isimova** [comment]
Thanks, this does solve the problem.

**Comment by smartschat** [comment]
I close the issue as the workaround solves the problem.
